<img src = "https://img.betapage.co/images/77640967-77641456.png" height=50% width = 50%>

In [114]:
import numpy as np
import array 

# Introduction to NumPy

"Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. This library provides you with an array data structure that holds some benefits over Python lists, such as: being more compact, faster access in reading and writing items, being more convenient and more efficient."


# What is a NumPy array?

"The central feature of NumPy is the array object class. Arrays are similar to lists in Python, except that every element of an array must be of the same type, typically a numeric type like float or int. Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists."

LINK: https://engineering.ucsb.edu/~shell/che210d/numpy.pdf

<img src = "http://community.datacamp.com.s3.amazonaws.com/community/production/ckeditor_assets/pictures/332/content_arrays-axes.png">

# NumPy Array Syntax
The function array takes two arguments: the list to be converted into the array and the type of each member of the list. 

In [115]:
#List to be converted
lst = [1,2,3,4,5,6,7,8,9]

arr = np.array(lst)
#print(lst)
#lst
print(arr)
arr


[1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Array elements are accessed, sliced, and manipulated just like lists.

In [116]:
#Index from the 2nd index on
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [117]:
#manipulate item at index 0
arr[0] = 10
arr

array([10,  2,  3,  4,  5,  6,  7,  8,  9])


<b>* Why can't we simply use a python list for these scientific computations?<b>

# Python List VS NumPy Array

"Arrays and lists are both used in Python to store data, but they don't serve exactly the same purposes. They both can be used to store any data type (real numbers, strings, etc), and they both can be indexed and iterated through, but the similarities between the two don't go much further. The main difference between a list and an array is the functions that you can perform to them. For example, you can divide an array by 3, and each number in the array will be divided by 3 and the result will be printed if you request it. If you try to divide a list by 3, Python will tell you that it can't be done, and an error will be thrown."


In [118]:
lst = [3,6,9,12,15,18,12]
lst/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [119]:
arr = np.array([3,6,9,12,15,18,12])
arr1 = arr * 4
print(arr1)

[12 24 36 48 60 72 48]


In [120]:
print(arr1)

[12 24 36 48 60 72 48]


Arrays can be multidimensional. Unlike lists, different axes are accessed using commas inside bracket notation. Here is an example with a two-dimensional array (e.g., a matrix)

In [121]:
lst1 = [1,2,3,4,5]\

lst2 = [5,6,7,8,9]
arr = np.array([lst2,lst1])
arr

array([[5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [122]:
(arr/3)

array([[1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667]])

In [123]:
lst_lst = [lst1,lst2]
arr = np.array(lst_lst)
print(lst_lst)
arr

[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]


array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [124]:
lst_lst/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

# Indexing Arrays VS Lists

In [125]:
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [126]:
print(arr[0,1])
arr[0][1]

2


2

In [127]:
print(lst_lst)
lst_lst

[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]


[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]

In [128]:
#lst_lst[0,1]
arr[0,1]

2

In [129]:
lst_lst[0][1]

2

In [130]:
arr[-1]

array([5, 6, 7, 8, 9])

In [131]:
lst_lst[-1]

[5, 6, 7, 8, 9]

In [132]:
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

<h3> How to index a multidemsional array? </h3><br>
The individual elements of arrays can be accessed in the same way as for lists.

<img src = "http://www.scipy-lectures.org/_images/numpy_indexing.png" height = 60% width = 60%>

In [133]:
list_2d = [[0,1,2,3,4,5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]]

In [134]:
myList = [1,2,3]
print(myList)

[1, 2, 3]


In [135]:
array_2d = np.array(list_2d)
print(array_2d)
array_2d.shape
#array_2d

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


(6, 6)

In [136]:
print(array_2d[0,3:5])

[3 4]


In [137]:
print(array_2d[4:,4:])

[[44 45]
 [54 55]]


In [138]:
print(array_2d[:,2])

[ 2 12 22 32 42 52]


In [139]:
print(array_2d[2:5:2,3::2]) # step by 2

[[23 25]
 [43 45]]


In [140]:
# adding new column to numpy array

In [141]:
calc = array_2d[:,5] * 1.05
# new_column = np.array(calc)
print(calc)
calc

[ 5.25 15.75 26.25 36.75 47.25 57.75]


array([ 5.25, 15.75, 26.25, 36.75, 47.25, 57.75])

In [145]:
new_array_2d = np.column_stack((array_2d,calc))
print(new_array_2d)

[[ 0.    1.    2.    3.    4.    5.    5.25]
 [10.   11.   12.   13.   14.   15.   15.75]
 [20.   21.   22.   23.   24.   25.   26.25]
 [30.   31.   32.   33.   34.   35.   36.75]
 [40.   41.   42.   43.   44.   45.   47.25]
 [50.   51.   52.   53.   54.   55.   57.75]]


# Changing Array to different DataType

In [39]:
mylist = arr.tolist()
print(mylist)
print(type(mylist))

[[5, 6, 7, 8, 9], [1, 2, 3, 4, 5]]
<class 'list'>


In [40]:
type(arr)

numpy.ndarray

In [41]:
arr = np.array(arr)
arr

array([[5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [43]:
type(arr)

numpy.ndarray

In [182]:
arr.shape

(2, 5)

# Change Array Shape

Transposed versions of arrays can also be generated, which will create a new array with the final two axes switched:

In [52]:
arr
print(type(arr))

<class 'numpy.ndarray'>


In [46]:
arr.shape

(2, 5)

In [47]:
arr.transpose()

array([[5, 1],
       [6, 2],
       [7, 3],
       [8, 4],
       [9, 5]])

In [48]:
arr.transpose().shape

(5, 2)

Make multidimensional array into one-dimensional array

In [49]:
arr.shape

(2, 5)

In [50]:
arr.flatten()

array([5, 6, 7, 8, 9, 1, 2, 3, 4, 5])

In [53]:
arr.flatten().shape
print(type(arr.flatten()))

<class 'numpy.ndarray'>


# Create New Array (Specific)

Numpy also provides many functions to create arrays.

Creates an array of all zeros with a specified shape.

In [56]:
#1-Dimensional
np.zeros(10, int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
#2-Dimensional
np.zeros((2,2), int)

array([[0, 0],
       [0, 0]])

Creates an array of all ones with a specified shape.

In [58]:
#1-Dimensional
np.ones(10, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [59]:
#2-Dimensional
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

Creates a constant array (specified number) with a specified shape.

In [60]:
#1-Dimensional
np.full(10,7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [61]:
#2-Dimensional
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

Created an array of a specified shape with random values.

In [62]:
#1-Dimensional
np.random.random(10)

array([0.7676577 , 0.18708201, 0.06955774, 0.13270188, 0.28383996,
       0.311552  , 0.55493215, 0.07069594, 0.5730394 , 0.84798343])

In [63]:
#2-Dimensional
np.random.random((2,2))

array([[0.37287484, 0.54907541],
       [0.178523  , 0.47284696]])

Create an array of a specified length with evenly spaced values.

In [186]:
#1-Dimensional
np.arange(10)
np.arange(1,10, 0.47368421)

array([1.        , 1.47368421, 1.94736842, 2.42105263, 2.89473684,
       3.36842105, 3.84210526, 4.31578947, 4.78947368, 5.26315789,
       5.7368421 , 6.21052631, 6.68421052, 7.15789473, 7.63157894,
       8.10526315, 8.57894736, 9.05263157, 9.52631578, 9.99999999])

Create an array with a specified "start", "stop", and number of values, evenly spaced.

In [65]:
#1-Dimensional
np.linspace(1, 10, num = 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

Creates a 2x2 identity matrix (array).

An identity matrix is a square matrix having 1s on the main diagonal, and 0s everywhere else. These are called identity matrices because, when you multiply them with a compatible matrix , you get back the same matrix.
http://www.sparknotes.com/math/algebra2/matrices/section3.rhtml

In [66]:
#2-Dimensional
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

OR

In [67]:
#2-Dimensional
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Math Functions using NumPy

"As such, it probably won’t surprise you that you can just use +, -, *, / or % to add, subtract, multiply, divide or calculate the remainder of two (or more) arrays. However, a big part of why NumPy is so handy, is because it also has functions to do this. The equivalent functions of the operations that you have seen just now are, respectively, np.add(), np.subtract(), np.multiply(), np.divide() and np.remainder()."

https://www.datacamp.com/community/tutorials/python-numpy-tutorial

In [68]:
arr = np.ones((10,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [69]:
np.add(arr,2)

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [72]:
#OR
arr + 2
#type(arr)

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [73]:
np.multiply(arr,3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [74]:
#OR
arr*2

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [75]:
np.subtract(arr,1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
#OR
arr -1 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [77]:
np.divide(arr,2)

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [78]:
#OR
arr/2

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [79]:
np.remainder(arr,1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [80]:
#OR
arr % 1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [81]:
arr.sum()

100.0

In [82]:
arr.min()

1.0

In [83]:
arr.max()

1.0

In [84]:
arr.mean()

1.0

# <font color = magenta> NumPy Problem 1 </font>
<font color = magenta>
Create the three arrays displayed in the image, below.

<img src = "https://i.stack.imgur.com/ojnFF.jpg">

In [190]:
#Array 1
lst = [[4,6,4],[1,1,8],[0,7,5],[5,3,3],[8,9,5]]
arr1 = np.array(lst)
arr1

array([[4, 6, 4],
       [1, 1, 8],
       [0, 7, 5],
       [5, 3, 3],
       [8, 9, 5]])

In [191]:
#Array 2
lst = [[8,8,4],[3,4,4],[0,0,9],[3,7,3],[3,4,7]]
arr2 = np.array(lst)
arr2

array([[8, 8, 4],
       [3, 4, 4],
       [0, 0, 9],
       [3, 7, 3],
       [3, 4, 7]])

In [192]:
#Array 3
lst = [[9,5,4],[7,7,3],[9,5,9],[8,7,8],[5,8,8]]
arr3 = np.array(lst)
arr3

array([[9, 5, 4],
       [7, 7, 3],
       [9, 5, 9],
       [8, 7, 8],
       [5, 8, 8]])

# <font color = magenta> NumPy Problem 2 </font>
<font color = magenta>
Create a multidimensional array of your dimension choice and fill it random values(not filled manually).

In [194]:
arr = np.random.random((3,4))

Find the min and max values of your array.

In [197]:
print(np.max(arr))
np.min(arr)

0.8992371611576009


0.21121295241782634

# <font color = magenta> NumPy Problem 3 </font>
<font color = magenta>
Create another multidimensional array of your dimension choice and fill it random values(not filled manually). Find the max value of your new array and replace it with your min value. Find the min value and replace it in your array with the max value.

In [243]:
arr = np.random.random((2,3))
print(arr)
print(np.unravel_index(np.argmax(arr), arr.shape))
print(np.unravel_index(np.argmin(arr), arr.shape))
arr[np.unravel_index(np.argmax(arr), arr.shape)], arr[np.unravel_index(np.argmin(arr), arr.shape)] = \
arr[np.unravel_index(np.argmin(arr), arr.shape)], arr[np.unravel_index(np.argmax(arr), arr.shape)] 
print(arr)

[[0.46398968 0.38997113 0.02509288]
 [0.49051492 0.79749971 0.78806293]]
(1, 1)
(0, 2)
[[0.46398968 0.38997113 0.79749971]
 [0.49051492 0.02509288 0.78806293]]


# <font color = magenta> NumPy Problem 4 </font>

Create a random vector of size 10 and sort it.

In [249]:
v = np.random.random(10)
print(v)
v_sort = np.sort(v)
print(v_sort)

[0.73061915 0.80843236 0.83561698 0.83820529 0.59629959 0.77791615
 0.48081186 0.25537735 0.01246948 0.906847  ]
[0.01246948 0.25537735 0.48081186 0.59629959 0.73061915 0.77791615
 0.80843236 0.83561698 0.83820529 0.906847  ]


# <font color = magenta> NumPy Problem 5 </font>

<font color = magenta>
How to swap two rows of an array?

In [271]:
arr = np.random.random((2,3))
print(arr)
#print(arr[[0]])
#print(arr[[1]])
print()
print(arr[[1, 0]])

[[0.85365787 0.20253809 0.53272729]
 [0.18775441 0.5810277  0.2282274 ]]

[[0.18775441 0.5810277  0.2282274 ]
 [0.85365787 0.20253809 0.53272729]]


# Numpy with Bay Area housing data set

In [2]:
def read_file_housing(filename):
    file_open = open(filename,"r")
    fixed_file = open("fixed-housing-data.csv","w")
    line_count = 0
    for line in iter(file_open):
        line_count += 1
        if "HomeID" in line:
            continue
        line_no_newline = line.rstrip()
        line1 = line_no_newline.replace("84085","94085") #Ex9
        line2 = line1.replace("84087","94087") #Ex9
        line3 = line2.replace("85014","95014") #Ex9
        line4 = line3.replace("85051","95051") #Ex9
        line5 = line4.replace("l","1") #Ex11 -- Car_Garage
        line_split = line5.split(",")
        if (int(line_split[5]) < 100): #Ex10 -- School_API
            line_split[5] = int(line_split[5]) * 10
        else:
            line_split[5] = int(line_split[5])
        line_split = [str(x) for x in line_split]
        myString = ",".join(line_split) + "\n"
        fixed_file.write(myString)
    file_open.close()
    fixed_file.close()
    return

In [3]:
read_file_housing("bayarea_home_prices.csv")

In [4]:
import numpy as np

In [5]:
"""
0 = HomeID
1 = HomeAge
2 = HomeSqft
3 = LotSize
4 = BedRooms
5 = HighSchoolAPI
6 = ProxFwy
7 = CarGarage
8 = ZipCode
9 = HomePriceK
"""

'\n0 = HomeID\n1 = HomeAge\n2 = HomeSqft\n3 = LotSize\n4 = BedRooms\n5 = HighSchoolAPI\n6 = ProxFwy\n7 = CarGarage\n8 = ZipCode\n9 = HomePriceK\n'

In [6]:
housing = np.loadtxt("fixed-housing-data.csv",
                          dtype=int,
                          delimiter=",")

In [7]:
print(housing[0:3])

[[    1    24  1757  6056     2   899     3     3 94085   894]
 [    2    10  1563  6085     2   959     4     3 94085   861]
 [    3    14  1344  6089     2   865     4     3 94085   831]]


In [8]:
print(housing.shape)

(100, 10)


In [9]:
# home prices
print(housing[:,9])

[ 894  861  831  809  890  867  843  820  874  885  903  912  933  865
  918  950  882  896  942  859  904  912  916  972  908  934  914  949
  919  953  991 1049 1042  994 1030 1019 1044 1038 1024  976 1115 1128
 1071 1059 1000 1185 1015 1114 1138 1068 1068 1097 1074 1114 1075 1130
 1116 1103 1080 1150 1177 1149 1163 1132 1138 1199 1179 1173 1128 1165
 1233 1180 1240 1242 1184 1173 1194 1181 1190 1182 1221 1288 1275 1300
 1272 1294 1219 1282 1256 1205 1252 1294 1269 1335 1267 1307 1336 1284
 1269 1250]


In [10]:
inflation = 0.1
print(housing[:,9] *(1+inflation) )

[ 983.4  947.1  914.1  889.9  979.   953.7  927.3  902.   961.4  973.5
  993.3 1003.2 1026.3  951.5 1009.8 1045.   970.2  985.6 1036.2  944.9
  994.4 1003.2 1007.6 1069.2  998.8 1027.4 1005.4 1043.9 1010.9 1048.3
 1090.1 1153.9 1146.2 1093.4 1133.  1120.9 1148.4 1141.8 1126.4 1073.6
 1226.5 1240.8 1178.1 1164.9 1100.  1303.5 1116.5 1225.4 1251.8 1174.8
 1174.8 1206.7 1181.4 1225.4 1182.5 1243.  1227.6 1213.3 1188.  1265.
 1294.7 1263.9 1279.3 1245.2 1251.8 1318.9 1296.9 1290.3 1240.8 1281.5
 1356.3 1298.  1364.  1366.2 1302.4 1290.3 1313.4 1299.1 1309.  1300.2
 1343.1 1416.8 1402.5 1430.  1399.2 1423.4 1340.9 1410.2 1381.6 1325.5
 1377.2 1423.4 1395.9 1468.5 1393.7 1437.7 1469.6 1412.4 1395.9 1375. ]


In [11]:
print(housing.sum(axis=0)) # sum by columns

[   5050    1720  161528  784050     271   90443     310     152 9455925
  108099]


In [25]:
print(housing[0:15])
print()
print(type(housing[0:15]))
print()
print(housing[0:15].sum(axis=1)) # sum by rows

[[    1    24  1757  6056     2   899     3     3 94085   894]
 [    2    10  1563  6085     2   959     4     3 94085   861]
 [    3    14  1344  6089     2   865     4     3 94085   831]
 [    4    14  1215  6129     3   959     4     2 94085   809]
 [    5    24  1866  6141     3   877     4     1 94085   890]
 [    6    18  1589  6148     2   920     3     0 94085   867]
 [    7    13  1947  6183     3   959     3     1 94085   843]
 [    8    19  1839  6186     3   905     4     0 94085   820]
 [    9    17  1501  6233     2   884     3     1 94085   874]
 [   10    24  1933  6276     2   950     4     1 94085   885]
 [   11    12  1798  6346     3   931     3     2 94085   903]
 [   12    22  1221  6430     3   904     2     1 94085   912]
 [   13    15  1541  6514     2   872     2     1 94085   933]
 [   14    25  1974  6547     2   857     4     3 94085   865]
 [   15    10  1510  6633     2   884     3     2 94085   918]]

<class 'numpy.ndarray'>

[103724 103574 103240 103224

In [37]:
homes_94085 = (housing[:,8] == 94085)
#print(housing[0:5,7:])
print(homes_94085)
print()
print(type(homes_94085))
homes_94085.ndim

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True False  True  True  True  True False
  True  True  True False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]

<class 'numpy.ndarray'>


1

In [62]:
data_94085 = housing[homes_94085]
print(data_94085)

[[    1    24  1757  6056     2   899     3     3 94085   894]
 [    2    10  1563  6085     2   959     4     3 94085   861]
 [    3    14  1344  6089     2   865     4     3 94085   831]
 [    4    14  1215  6129     3   959     4     2 94085   809]
 [    5    24  1866  6141     3   877     4     1 94085   890]
 [    6    18  1589  6148     2   920     3     0 94085   867]
 [    7    13  1947  6183     3   959     3     1 94085   843]
 [    8    19  1839  6186     3   905     4     0 94085   820]
 [    9    17  1501  6233     2   884     3     1 94085   874]
 [   10    24  1933  6276     2   950     4     1 94085   885]
 [   11    12  1798  6346     3   931     3     2 94085   903]
 [   12    22  1221  6430     3   904     2     1 94085   912]
 [   13    15  1541  6514     2   872     2     1 94085   933]
 [   14    25  1974  6547     2   857     4     3 94085   865]
 [   15    10  1510  6633     2   884     3     2 94085   918]
 [   17    23  1464  6773     3   965     4     2 94085

In [16]:
sum_price_94085 = data_94085[:,9].sum()
print(sum_price_94085)


22149


In [17]:
print(len(data_94085))

25


In [18]:
print(data_94085.shape[0])

25


In [19]:
print(data_94085.shape[1])

10


In [20]:
average_94085 = sum_price_94085/25
print(average_94085)

885.96


# NumPy Problem 6
### Calculate average price in each zip code: 94085, 94087, 95014, 95051
### Calculate minimum and max price in each zip code: 94085, 94087, 95014, 95051
### Calculate standard deviation of price in each zip code: 94085, 94087, 95014, 95051

In [80]:
# Your code here
lst = [94085, 94087, 95014, 95051]
print("zip_code", "average_price", "min_price", "max_price", "standard_deviation_price")

for z in lst:
    homes_zip = (housing[:,8] == z)
    data_zip = housing[homes_zip]
    price_zip = data_zip[:, 9]
    price_zip_mean = price_zip.mean()
    price_zip_min = price_zip.min()
    price_zip_max = price_zip.max()
    price_zip_std = np.std(price_zip)
    print(z, price_zip_mean, price_zip_min, price_zip_max, price_zip_std)
    

zip_code average_price min_price max_price standard_deviation_price
94085 885.96 809 934 33.71347505078644
94087 1151.48 1103 1190 27.56536957851282
95014 1263.32 1194 1336 37.73986751434085
95051 1023.2 942 1097 46.03563836855095


In [81]:
h1 = housing[housing[:,5].argsort()] # by school_api ascending
print(housing[:,5].argsort())
print(h1)

[64 72 22 19 78 76 18 31 94 25 98 52 66 99 13 43 84 93  2 51 41 63 61 12
 73 55 81  4 89 86 69 88 57 79 14  8 53 70 48 54 47 39 27 71 80 15  0 24
 28 60 46 65 59 21 11  7 23 95 42 97 45 40 30 91  5 20 85 35 77 62 87 83
 10 29 17 33 74 67 90 82 92 96 38 50 49  9 56 58 75  6 32  3  1 44 36 68
 16 26 34 37]
[[   65    14  1617  8394     2   850     2     0 94087  1138]
 [   73    25  1302  8668     3   850     4     2 95014  1240]
 [   23    15  1828  6956     3   851     4     3 94085   916]
 [   20    13  1358  6819     2   851     3     2 94085   859]
 [   79    17  1373  8953     2   851     2     0 94087  1190]
 [   77    17  1881  8921     3   852     2     0 95014  1194]
 [   19    10  1246  6810     2   853     4     3 95051   942]
 [   32    18  1866  7181     2   854     2     3 95051  1049]
 [   95    13  1582  9339     3   856     3     0 95014  1267]
 [   26    12  1500  7025     2   856     4     2 94085   934]
 [   99    19  1880  9470     3   857     3     3 95014  1269]
 

In [23]:
h2 = housing[housing[:,5].argsort()[::-1]] # by school_api descending
print(h2)

[[   38    22  1724  7339     3   975     3     3 95051  1038]
 [   35    12  1943  7249     2   974     2     0 95051  1030]
 [   27    13  1836  7027     2   966     3     3 94085   914]
 [   17    23  1464  6773     3   965     4     2 94085   882]
 [   69    21  1575  8579     2   962     4     3 94087  1128]
 [   37    13  1874  7333     3   960     3     2 95051  1044]
 [   45    15  1249  7609     3   960     2     2 95051  1000]
 [    2    10  1563  6085     2   959     4     3 94085   861]
 [    4    14  1215  6129     3   959     4     2 94085   809]
 [   33    11  1953  7199     3   959     3     2 95051  1042]
 [    7    13  1947  6183     3   959     3     1 94085   843]
 [   76    12  1947  8882     3   954     3     2 94087  1173]
 [   59    22  1559  8096     2   953     2     3 95051  1080]
 [   57    11  1927  7983     3   950     3     1 94087  1116]
 [   10    24  1933  6276     2   950     4     1 94085   885]
 [   50    19  1836  7803     3   949     3     0 95051

# NumPy Problem 7
### Find top-2 listings by School API for all zipcodes

In [105]:
# Your code here
lst = [94085, 94087, 95014, 95051]

for z in lst:
    homes_zip = (housing[:,8] == z)
    data_zip = housing[homes_zip]
    #print(data_zip)
    #print()
    #print(data_zip[:,5].argsort())
    api_zip = data_zip[data_zip[:,5].argsort()[::-1]]
    print("top-2 listings by School API for zipcode {}".format(z))
    print(api_zip[0:2])


top-2 listings by School API for zipcode 94085
[[   27    13  1836  7027     2   966     3     3 94085   914]
 [   17    23  1464  6773     3   965     4     2 94085   882]]
top-2 listings by School API for zipcode 94087
[[   69    21  1575  8579     2   962     4     3 94087  1128]
 [   76    12  1947  8882     3   954     3     2 94087  1173]]
top-2 listings by School API for zipcode 95014
[[   97    10  1645  9352     4   942     3     3 95014  1336]
 [   93    25  1298  9309     3   942     3     0 95014  1269]]
top-2 listings by School API for zipcode 95051
[[   38    22  1724  7339     3   975     3     3 95051  1038]
 [   35    12  1943  7249     2   974     2     0 95051  1030]]


# NumPy Problem 8
### Prices are expected to go up by 4% next year.
### Add another column with predicted prices

In [177]:
# Your code here
print(housing[0:2])
price = housing[:, 9]
#print(price)
price_next_year = np.int16(price * 1.04)

#print(price_next_year)

print()

housing_new = np.column_stack((housing, price_next_year))
print(housing_new)


[[    1    24  1757  6056     2   899     3     3 94085   894]
 [    2    10  1563  6085     2   959     4     3 94085   861]]

[[    1    24  1757 ... 94085   894   929]
 [    2    10  1563 ... 94085   861   895]
 [    3    14  1344 ... 94085   831   864]
 ...
 [   98    21  1312 ... 95014  1284  1335]
 [   99    19  1880 ... 95014  1269  1319]
 [  100    11  1691 ... 95014  1250  1300]]


# NumPy Problem 9
### Sort the matrix based on home prices. Save the updated numpy matrix with added column in Problem 8 to a file.

In [185]:
# Your code here
housing_sort = housing_new[housing_new[:,9].argsort()]
print(housing_sort)


fixed_file = open("my_fixed-housing-data.csv","w")

for i in range(100):
    housing_sort_str = [str(x) for x in housing_sort[i]]
    myString = ",".join(housing_sort_str) + "\n"
    print(myString)
    fixed_file.write(myString)
fixed_file.close()

[[    4    14  1215 ... 94085   809   841]
 [    8    19  1839 ... 94085   820   852]
 [    3    14  1344 ... 94085   831   864]
 ...
 [   96    11  1981 ... 95014  1307  1359]
 [   94    21  1983 ... 95014  1335  1388]
 [   97    10  1645 ... 95014  1336  1389]]
4,14,1215,6129,3,959,4,2,94085,809,841

8,19,1839,6186,3,905,4,0,94085,820,852

3,14,1344,6089,2,865,4,3,94085,831,864

7,13,1947,6183,3,959,3,1,94085,843,876

20,13,1358,6819,2,851,3,2,94085,859,893

2,10,1563,6085,2,959,4,3,94085,861,895

14,25,1974,6547,2,857,4,3,94085,865,899

6,18,1589,6148,2,920,3,0,94085,867,901

9,17,1501,6233,2,884,3,1,94085,874,908

17,23,1464,6773,3,965,4,2,94085,882,917

10,24,1933,6276,2,950,4,1,94085,885,920

5,24,1866,6141,3,877,4,1,94085,890,925

1,24,1757,6056,2,899,3,3,94085,894,929

18,16,1572,6809,2,935,2,0,94085,896,931

11,12,1798,6346,3,931,3,2,94085,903,939

21,17,1246,6870,3,922,4,3,94085,904,940

25,21,1991,7022,2,900,3,1,94085,908,944

22,10,1752,6892,3,904,3,0,94085,912,948

12,22,1

# <font color = magenta> NumPy Problem 10 </font>

Write a function that takes a long string containing multiple words. Print the same string, except with the words in backwards order. 

<i>HINT: Use <b>YOUR_STRING<code>.split()</code></b> function<br></i>

In [186]:
myString = "Python for Data Science class is on Saturdays for seven weeks."

In [195]:
def str_in_backwards_order(str):
    str = str.rstrip(".")
    str_lst = str.split()
    #print(type(str_lst))
    str_lst_backwards = str_lst[::-1]
    #print(str_lst_backwards)
    new_string = " ".join(str_lst_backwards)
    print(new_string + ".")

    
str_in_backwards_order(myString)

weeks seven for Saturdays on is class Science Data for Python.
